defmodule BDDCompiler.Emitter do
  @moduledoc """
  将校验通过的 DSL AST 编译为确定性的 ExUnit 测试源码（字符串）。

  注意：生成代码会调用业务项目提供的 runtime module（运行期指令实现）。
  """

  alias BDDCompiler.CompileError

  @spec emit_to_string(String.t(), [BDDCompiler.DslParser.scenario()], keyword()) :: String.t()
  def emit_to_string(source_id, scenarios, opts \\ [])
      when is_binary(source_id) and is_list(scenarios) and is_list(opts) do
    base = Keyword.get(opts, :module_base, Path.basename(source_id, ".dsl"))

    runtime_module = Keyword.get(opts, :runtime_module, "Shop.BDD.Instructions.V1") |> module_from_string!()
    test_case = Keyword.get(opts, :test_case, "Shop.DataCase") |> module_from_string!()
    module_prefix = Keyword.get(opts, :module_prefix, "Shop.BDD.Generated") |> module_prefix_from_string!()

    mod = Module.concat(module_prefix ++ [Macro.camelize(base) <> "Test"])

    header = [
      "# Generated by bdd_compiler from #{source_id}. DO NOT EDIT.",
      "",
      "defmodule #{inspect(mod)} do",
      "  use #{inspect(test_case)}, async: false",
      "",
      "  @moduletag :bdd_generated",
      ""
    ]

    body =
      scenarios
      |> Enum.flat_map(fn scenario ->
        emit_scenario(scenario, runtime_module)
      end)

    footer = ["end", ""]

    (header ++ body ++ footer)
    |> Enum.join("\n")
  end

  defp emit_scenario(%{id: id, title: title, tags: tags, steps: steps}, runtime_module) do
    test_name =
      ["[", id, "] ", title]
      |> Enum.join("")
      |> String.trim()

    tag_lines =
      tags
      |> Enum.sort()
      |> Enum.map(fn tag -> "  @tag #{inspect(tag)}" end)

    meta_comment = "  # Source: #{id}"

    test_lines =
      [
        meta_comment
        | tag_lines
      ] ++
        [
          "  test #{inspect(test_name)} do",
          "    run_id = #{inspect(runtime_module)}.new_run_id()",
          "    ctx = %{run_id: run_id, scenario_id: #{inspect(id)}}"
        ] ++
        Enum.flat_map(steps, &emit_step(&1, runtime_module)) ++
        [
          "    _ctx = ctx",
          "    :ok",
          "  end",
          ""
        ]

    test_lines
  end

  defp emit_step({:let, name, expr, meta}, runtime_module) do
    [
      "    # line #{meta.line}: #{String.trim(meta.raw)}",
      "    ctx = Map.put(ctx, #{inspect(name)}, #{emit_expr(expr, meta, runtime_module)})"
    ]
  end

  defp emit_step({kind, instruction, args, meta}, runtime_module) when kind in [:given, :when, :then] do
    [
      "    # line #{meta.line}: #{String.trim(meta.raw)}",
      "    ctx = #{inspect(runtime_module)}.run_step!(ctx, #{inspect(kind)}, #{inspect(instruction)}, #{emit_args(args, meta, runtime_module)}, #{emit_meta(meta)}, #{inspect(meta[:line])})"
    ]
  end

  defp emit_step(other, _runtime_module) do
    raise CompileError, message: "无法 emit 的步骤：#{inspect(other)}"
  end

  defp emit_args(args, meta, runtime_module) do
    # 按 key 排序，确保确定性
    pairs =
      args
      |> Enum.sort_by(fn {k, _v} -> Atom.to_string(k) end)
      |> Enum.map(fn {k, v} -> {k, emit_expr(v, meta, runtime_module)} end)

    inner =
      pairs
      |> Enum.map(fn {k, v_src} -> "#{k}: #{v_src}" end)
      |> Enum.join(", ")

    "%{#{inner}}"
  end

  defp emit_expr({:var, name}, meta, runtime_module) do
    "#{inspect(runtime_module)}.get!(ctx, #{inspect(name)}, #{emit_meta(meta)})"
  end

  defp emit_expr({:call, :uuid, []}, _meta, _runtime_module), do: "Ecto.UUID.generate()"
  defp emit_expr({:call, :now, []}, _meta, runtime_module), do: "#{inspect(runtime_module)}.now(ctx)"
  defp emit_expr({:call, :run_id, []}, _meta, _runtime_module), do: "to_string(Map.get(ctx, :run_id))"
  defp emit_expr({:call, :dt, [s]}, _meta, runtime_module), do: "#{inspect(runtime_module)}.dt!(#{inspect(s)})"
  defp emit_expr({:call, :date, [s]}, _meta, _runtime_module), do: "Date.from_iso8601!(#{inspect(s)})"
  defp emit_expr({:call, :dec, [s]}, _meta, _runtime_module), do: "Decimal.new(#{inspect(s)})"
  defp emit_expr({:int, i}, _meta, _runtime_module), do: Integer.to_string(i)
  defp emit_expr({:bool, b}, _meta, _runtime_module), do: if(b, do: "true", else: "false")
  defp emit_expr({:str, s}, _meta, _runtime_module), do: inspect(s)

  defp emit_expr(other, meta, _runtime_module) do
    raise CompileError,
      message: "不支持的表达式 emit：#{inspect(other)}",
      file: meta[:file],
      line: meta[:line],
      raw: meta[:raw]
  end

  defp emit_meta(meta) do
    file = meta[:file]
    line = meta[:line]
    raw = meta[:raw]

    "%{file: #{inspect(file)}, line: #{inspect(line)}, raw: #{inspect(raw)}}"
  end

  defp module_from_string!(mod) when is_atom(mod), do: mod

  defp module_from_string!(mod) when is_binary(mod) do
    mod
    |> String.split(".")
    |> Enum.map(&String.to_atom/1)
    |> Module.concat()
  end

  defp module_prefix_from_string!(prefix) when is_atom(prefix), do: [prefix]

  defp module_prefix_from_string!(prefix) when is_binary(prefix) do
    prefix
    |> String.split(".")
    |> Enum.map(&String.to_atom/1)
  end
end

