defmodule BDDCompiler.GoEmitter do
  @moduledoc """
  将校验通过的 DSL AST 编译为 godog（Go BDD 框架）测试源码（字符串）。

  输出 Go 测试文件，包含 godog step 注册和 runtime.RunStep 调用。
  """

  alias BDDCompiler.CompileError

  @spec emit_to_string(String.t(), [BDDCompiler.DslParser.scenario()], keyword()) :: String.t()
  def emit_to_string(source_id, scenarios, opts \\ [])
      when is_binary(source_id) and is_list(scenarios) and is_list(opts) do
    module_prefix = Keyword.get(opts, :module_prefix, "myapp")

    header = build_header(source_id, module_prefix)
    functions = Enum.map(scenarios, &emit_scenario/1)

    # 生成 initializeScenario 函数，调用所有 init 函数
    init_calls =
      scenarios
      |> Enum.map(fn s -> "\t#{init_func_name(s.id)}(sc)" end)

    initialize_scenario = [
      "func initializeScenario(sc *godog.ScenarioContext) {",
      Enum.join(init_calls, "\n"),
      "}",
      ""
    ]

    [
      header,
      Enum.join(functions, "\n"),
      Enum.join(initialize_scenario, "\n")
    ]
    |> Enum.join("\n")
  end

  # 构建 Go 文件头部：package 声明、import、TestFeatures 函数
  defp build_header(source_id, module_prefix) do
    [
      "// Generated by bdd_compiler from #{source_id}. DO NOT EDIT.",
      "",
      "package bdd_test",
      "",
      "import (",
      "\t\"testing\"",
      "",
      "\t\"github.com/cucumber/godog\"",
      "\t\"#{module_prefix}/bdd/runtime\"",
      ")",
      "",
      "func TestFeatures(t *testing.T) {",
      "\tsuite := godog.TestSuite{",
      "\t\tScenarioInitializer: initializeScenario,",
      "\t\tOptions: &godog.Options{",
      "\t\t\tFormat:   \"pretty\",",
      "\t\t\tPaths:    []string{\"features\"},",
      "\t\t\tTestingT: t,",
      "\t\t},",
      "\t}",
      "\tsuite.Run()",
      "}",
      ""
    ]
    |> Enum.join("\n")
  end

  # 为每个 scenario 生成 init 函数
  defp emit_scenario(%{id: id, steps: steps}) do
    func_name = init_func_name(id)

    step_lines =
      steps
      |> Enum.flat_map(&emit_step/1)
      |> Enum.map(fn line -> "\t" <> line end)

    lines = [
      "func #{func_name}(sc *godog.ScenarioContext) {",
      "\tctx := make(map[string]interface{})",
      ""
    ] ++ step_lines ++ [
      "}",
      ""
    ]

    Enum.join(lines, "\n")
  end

  # LET 绑定 → ctx 赋值
  defp emit_step({:let, name, expr, meta}) do
    [
      "// line #{meta.line}: #{String.trim(meta.raw)}",
      "ctx[#{go_string(Atom.to_string(name))}] = #{emit_expr(expr)}",
      ""
    ]
  end

  # GIVEN/WHEN/THEN → sc.Given/When/Then + runtime.RunStep
  defp emit_step({kind, instruction, args, meta}) when kind in [:given, :when, :then] do
    sc_method = kind |> Atom.to_string() |> String.capitalize()
    kind_str = Atom.to_string(kind)
    instr_str = Atom.to_string(instruction)

    # 构建 regex pattern（使用 scenario ID + instruction name）
    regex = "^#{instr_str}$"

    # 构建 args map
    args_str = emit_go_args(args)

    [
      "// line #{meta.line}: #{String.trim(meta.raw)}",
      "sc.#{sc_method}(`#{regex}`, func() error {",
      "\treturn runtime.RunStep(ctx, #{go_string(kind_str)}, #{go_string(instr_str)}, #{args_str})",
      "})",
      ""
    ]
  end

  defp emit_step(other) do
    raise CompileError, message: "无法 emit 的步骤：#{inspect(other)}"
  end

  # 生成 Go map[string]interface{} 字面量
  defp emit_go_args(args) when map_size(args) == 0 do
    "map[string]interface{}{}"
  end

  defp emit_go_args(args) do
    pairs =
      args
      |> Enum.sort_by(fn {k, _v} -> Atom.to_string(k) end)
      |> Enum.map(fn {k, v} ->
        "\t#{go_string(Atom.to_string(k))}: #{emit_expr(v)},"
      end)

    inner = Enum.join(pairs, "\n")
    "map[string]interface{}{\n#{inner}\n}"
  end

  # 表达式映射：DSL 表达式 → Go 表达式
  defp emit_expr({:var, name}), do: "ctx[#{go_string(Atom.to_string(name))}]"
  defp emit_expr({:call, :uuid, []}), do: "uuid.New().String()"
  defp emit_expr({:call, :now, []}), do: "time.Now()"
  defp emit_expr({:call, :run_id, []}), do: "ctx[\"run_id\"]"
  defp emit_expr({:call, :dt, [s]}), do: "runtime.ParseDatetime(#{go_string(s)})"
  defp emit_expr({:call, :date, [s]}), do: "runtime.ParseDate(#{go_string(s)})"
  defp emit_expr({:call, :dec, [s]}), do: "decimal.NewFromString(#{go_string(s)})"
  defp emit_expr({:int, i}), do: Integer.to_string(i)
  defp emit_expr({:bool, true}), do: "true"
  defp emit_expr({:bool, false}), do: "false"
  defp emit_expr({:str, s}), do: go_string(s)

  defp emit_expr(other) do
    raise CompileError, message: "不支持的表达式 emit：#{inspect(other)}"
  end

  # Go 字符串字面量
  defp go_string(s) when is_binary(s) do
    escaped =
      s
      |> String.replace("\\", "\\\\")
      |> String.replace("\"", "\\\"")
      |> String.replace("\n", "\\n")
      |> String.replace("\t", "\\t")

    "\"#{escaped}\""
  end

  # 从 scenario ID 生成 Go 函数名（驼峰格式）
  defp init_func_name(id) do
    camel =
      id
      |> String.replace(~r/[^a-zA-Z0-9]+/, "_")
      |> String.split("_", trim: true)
      |> Enum.map(&String.capitalize/1)
      |> Enum.join("")

    "init#{camel}"
  end
end
