//! 架构健康度评分模块
//!
//! 提供架构健康度评分功能，支持多维度评分、自定义配置和多种输出格式。
//!
//! # 使用示例
//!
//! ```bash
//! # 基本评分
//! bcc arch score --input validation-results/
//!
//! # 使用自定义配置
//! bcc arch score --input validation-results/ --config arch-score.yaml
//!
//! # 生成配置文件模板
//! bcc arch score init-config --output my-config.yaml --template strict
//! ```

pub mod calculator;
pub mod cli;
pub mod config;
pub mod context;
pub mod dimensions;
pub mod models;
pub mod output;

pub use calculator::{ScoreCalculator, ScoringMode};
pub use config::ScoringConfig;
pub use context::ScoringContext;
pub use models::{ArchitectureScore, DimensionScore, Grade, Severity};



/// 执行评分命令
pub fn score(
    input: &str,
    config: Option<&str>,
    mode: &str,
    format: &str,
    output: Option<&str>,
    threshold: f64,
    verbose: bool,
    smell_report: Option<&str>,
) {
    if let Err(e) = score_impl(input, config, mode, format, output, threshold, verbose, smell_report) {
        eprintln!("[score] error: {}", e);
        std::process::exit(1);
    }
}

fn score_impl(
    input: &str,
    config: Option<&str>,
    mode: &str,
    format: &str,
    output: Option<&str>,
    threshold: f64,
    verbose: bool,
    smell_report: Option<&str>,
) -> Result<(), String> {
    // 加载配置
    let config = match config {
        Some(path) => ScoringConfig::from_file(path)?,
        None => ScoringConfig::default(),
    };

    // 解析模式
    let scoring_mode = match mode {
        "strict" => ScoringMode::Strict,
        "lenient" => ScoringMode::Lenient,
        "warning" => ScoringMode::Warning,
        _ => return Err(format!("invalid mode '{}': expected strict|lenient|warning", mode)),
    };

    // 构建评分上下文
    let ctx = ScoringContext::from_input_dir(input)?;

    // 创建评分器（若传了 smell_report，追加 code_quality 维度）
    let mut calculator = ScoreCalculator::new(config.clone(), scoring_mode);
    if let Some(path) = smell_report {
        let cq = &config.dimensions.code_quality;
        calculator.add_dimension(Box::new(
            dimensions::code_quality::CodeQualityDimension::new(
                cq.weight,
                cq.blocking,
                cq.config.threshold,
                Some(path.to_string()),
            ),
        ));
    }

    // 计算评分
    let score = calculator.calculate(&ctx);

    // 格式化输出
    let output_content = match format {
        "json" => output::format_json(&score, verbose)?,
        "markdown" | "md" => output::format_markdown(&score, verbose)?,
        "text" | _ => output::format_text(&score, verbose)?,
    };

    // 输出结果
    match output {
        Some(path) => {
            std::fs::write(path, output_content)
                .map_err(|e| format!("write output failed: {}", e))?;
            println!("score_report_written={}", path);
        }
        None => {
            println!("{}", output_content);
        }
    }

    // 根据阈值决定退出码
    if !score.passed || score.total < threshold {
        eprintln!(
            "[score] failed: score={:.1} (threshold={:.1})",
            score.total, threshold
        );
        std::process::exit(2);
    }

    println!("[score] passed: score={:.1}", score.total);
    Ok(())
}

/// 生成默认配置
pub fn init_config(output: &str, template: &str) {
    if let Err(e) = init_config_impl(output, template) {
        eprintln!("[score] error: {}", e);
        std::process::exit(1);
    }
}

fn init_config_impl(output: &str, template: &str) -> Result<(), String> {
    let config = match template {
        "strict" => ScoringConfig::strict_template(),
        "lenient" => ScoringConfig::lenient_template(),
        "minimal" => ScoringConfig::minimal_template(),
        "default" => ScoringConfig::default(),
        _ => {
            return Err(format!(
                "invalid template '{}': expected default|strict|lenient|minimal",
                template
            ))
        }
    };

    let yaml = serde_yaml::to_string(&config)
        .map_err(|e| format!("serialize config failed: {}", e))?;

    // 添加文件头注释
    let content = format!(
        "# Architecture Scoring Configuration\n# Template: {}\n# Generated by bcc arch score init-config\n\n{}",
        template, yaml
    );

    std::fs::write(output, content)
        .map_err(|e| format!("write config failed: {}", e))?;

    println!("config_template_written={}", output);
    Ok(())
}

/// 对比多个版本
pub fn compare(
    inputs: &[String],
    labels: &[String],
    format: &str,
    output: Option<&str>,
) {
    if let Err(e) = compare_impl(inputs, labels, format, output) {
        eprintln!("[score] error: {}", e);
        std::process::exit(1);
    }
}

fn compare_impl(
    inputs: &[String],
    labels: &[String],
    format: &str,
    output: Option<&str>,
) -> Result<(), String> {
    if inputs.len() < 2 {
        return Err("at least 2 inputs required for comparison".into());
    }
    if !labels.is_empty() && labels.len() != inputs.len() {
        return Err(format!(
            "labels count ({}) must match inputs count ({})",
            labels.len(),
            inputs.len()
        ));
    }

    let config = ScoringConfig::default();
    let calculator = ScoreCalculator::new(config, ScoringMode::Strict);

    let mut results = Vec::new();
    for (i, input) in inputs.iter().enumerate() {
        let label = labels
            .get(i)
            .cloned()
            .unwrap_or_else(|| format!("v{}", i + 1));
        let ctx = ScoringContext::from_input_dir(input)?;
        let score = calculator.calculate(&ctx);
        results.push((label, score));
    }

    let content = match format {
        "json" => output::format_comparison_json(&results)?,
        _ => output::format_comparison_markdown(&results)?,
    };

    match output {
        Some(path) => {
            std::fs::write(path, content)
                .map_err(|e| format!("write output failed: {}", e))?;
            println!("comparison_report_written={}", path);
        }
        None => println!("{}", content),
    }

    Ok(())
}
